# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
Defaults: &defaults
  encryption_key: '<Run rake secret to get a value to put here>'

development:
  <<: *defaults

  admin_name: Administrator
  admin_email: admin@example.com
  admin_password: changeme

  secret_key_base: '<Run rake secret to get a value to put here>'
  application_code: amasynsoftware
  application_name: 'Amasyn Software'
  application_url: amasynsoftware.ngrok.com

  domain_name: amasynsoftware.ngrok.com
  email_provider_username: admin@example.com
  email_provider_password: changeme

test:
  <<: *defaults

  secret_key_base: '<Run rake secret to get a value to put here>'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *defaults

  secret_key_base: '<Run rake secret to get a value to put here. You might also want to load the value from the environment using something like <%= ENV["SECRET_KEY_BASE"] %> >'

  encryption_key: '<Run rake secret to get a value to put here You might also want to load the value from the environment using something like <%= ENV["ENCRYPTION_KEY"] %>>'
